-- ***************************************************************************************
-- File components.vhd auto-generated by packaging utiltiy on Tue Mar 10 16:32:44 2009 GMT
-- ***************************************************************************************

library ieee;
use ieee.std_logic_1164.all;

package components is
component COREAPBNVM 
   GENERIC (
      FAMILY               : INTEGER := 17;
      APB_AWIDTH           : INTEGER := 8;
      APB_DWIDTH           : INTEGER := 8;
      NUM_INSTANCES        : INTEGER := 1;
      -- Init/Config parameters
      INIT_ENABLED         : INTEGER := 0;
      INIT_AWIDTH          : INTEGER := 11;
      INIT_BASE_ADDRESS_RST : INTEGER := 0;
      INIT_WORD_COUNT_RST  : INTEGER := 0;
      INIT_SPARE_PAGE_RST  : INTEGER := 0;
      INIT_BASE_ADDRESS_0  : INTEGER := 0;
      INIT_WORD_COUNT_0    : INTEGER := 0;
      INIT_SPARE_PAGE_0    : INTEGER := 0;
      INIT_BASE_ADDRESS_1  : INTEGER := 0;
      INIT_WORD_COUNT_1    : INTEGER := 0;
      INIT_SPARE_PAGE_1    : INTEGER := 0;
      INIT_BASE_ADDRESS_2  : INTEGER := 0;
      INIT_WORD_COUNT_2    : INTEGER := 0;
      INIT_SPARE_PAGE_2    : INTEGER := 0;
      INIT_BASE_ADDRESS_3  : INTEGER := 0;
      INIT_WORD_COUNT_3    : INTEGER := 0;
      INIT_SPARE_PAGE_3    : INTEGER := 0
   );
   PORT (
      --APB IO
      --inputs
      PCLK                 : IN STD_LOGIC;
      PRESETN              : IN STD_LOGIC;
      PSEL                 : IN STD_LOGIC;
      PENABLE              : IN STD_LOGIC;
      PWRITE               : IN STD_LOGIC;
      PADDR                : IN STD_LOGIC_VECTOR(APB_AWIDTH-1 DOWNTO 0);
      PWDATA               : IN STD_LOGIC_VECTOR(APB_DWIDTH-1 DOWNTO 0);
      --outputs
      PRDATA               : OUT STD_LOGIC_VECTOR(APB_DWIDTH-1 DOWNTO 0);
      PREADY               : OUT STD_LOGIC;
      PSLVERR              : OUT STD_LOGIC;
      -- 14Aug08, AS added:
      -- INIT / CFG signals
      -- inputs
      INIT_BASE0           : IN STD_LOGIC;
      INIT_BASE1           : IN STD_LOGIC;
      INIT_BASE2           : IN STD_LOGIC;
      INIT_BASE3           : IN STD_LOGIC;
      -- outputs
      INIT_DONE            : OUT STD_LOGIC;
      INIT_DATA            : OUT STD_LOGIC_VECTOR(8 DOWNTO 0);
      INIT_ADDR            : OUT STD_LOGIC_VECTOR(INIT_AWIDTH-1 DOWNTO 0);
      INIT_DATVAL          : OUT STD_LOGIC
   );
end component;

end components;