@TM:1277113832
@N: FP130 :"":0:0:0:-1|Promoting Net PCLK_c on CLKBUF  PCLK_pad 
@N: MF249 :"":0:0:0:-1|Running in 32-bit mode.
@N: MF258 :"":0:0:0:-1|Gated clock conversion disabled 
@N: MT320 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT322 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@W: MT420 :"":0:0:0:-1|Found inferred clock FlashApb|PCLK with period 10.00ns. A user-defined clock should be declared on object "p:PCLK"
@N: CD630 :"C:\Actelprj\AFS_ADV_KIT_8051\hdl\flash_control.vhd":8:7:8:14|M
@W: CL159 :"C:\Actelprj\AFS_ADV_KIT_8051\hdl\flash_control.vhd":20:8:20:15|M
@W: CL159 :"C:\Actelprj\AFS_ADV_KIT_8051\hdl\flash_control.vhd":22:8:22:12|M
@N: CD630 :"C:\Actelprj\AFS_ADV_KIT_8051\smartgen\nvm64k\nvm64k.vhd":8:7:8:12|M
@W: CL168 :"C:\Actelprj\AFS_ADV_KIT_8051\smartgen\nvm64k\nvm64k.vhd":146:4:146:18|M
@N: CD630 :"D:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\fusion.vhd":1899:10:1899:12|M
@N: CD630 :"D:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\fusion.vhd":3019:10:3019:12|M
@N: CD630 :"D:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\fusion.vhd":4477:10:4477:12|M
@N: CD720 :"D:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\vhd\std.vhd":123:18:123:21|M
