@TM:1272354342
@N: FP130 :"":0:0:0:-1|Promoting Net SYSCLK_c on CLKBUF  SYSCLK_pad 
@N: MF249 :"":0:0:0:-1|Running in 32-bit mode.
@N: MF258 :"":0:0:0:-1|Gated clock conversion disabled 
@N: MT320 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT322 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@W: MT420 :"":0:0:0:-1|Found inferred clock mem_decode|SYSCLK with period 10.00ns. A user-defined clock should be declared on object "p:SYSCLK"
@N: CD630 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\fusion.vhd":1491:10:1491:13|M
@N: CD630 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\fusion.vhd":1899:10:1899:12|M
@N: CD630 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\fusion.vhd":2117:10:2117:12|M
@N: CD630 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\fusion.vhd":2179:10:2179:12|M
@N: CD630 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\fusion.vhd":2381:10:2381:12|M
@N: CD630 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\fusion.vhd":3019:10:3019:12|M
@N: CD630 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\fusion.vhd":3149:10:3149:13|M
@N: CD630 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\fusion.vhd":3182:10:3182:15|M
@N: CD720 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\vhd\std.vhd":123:18:123:21|M
@N: CD630 :"C:\Actelprj\AFS_ADV_KIT_8051\hdl\memory_interface.vhd":7:7:7:16|M
@W: CL246 :"C:\Actelprj\AFS_ADV_KIT_8051\hdl\memory_interface.vhd":14:8:14:11|M
@W: CD638 :"C:\Actelprj\AFS_ADV_KIT_8051\hdl\memory_interface.vhd":38:7:38:16|M
@W: CD638 :"C:\Actelprj\AFS_ADV_KIT_8051\hdl\memory_interface.vhd":39:7:39:16|M
@W: CD638 :"C:\Actelprj\AFS_ADV_KIT_8051\hdl\memory_interface.vhd":40:7:40:16|M
@N: CD630 :"C:\Actelprj\AFS_ADV_KIT_8051\smartgen\INT_RAM8kX8\INT_RAM8kX8.vhd":8:7:8:17|M
@W: CL168 :"C:\Actelprj\AFS_ADV_KIT_8051\smartgen\INT_RAM8kX8\INT_RAM8kX8.vhd":346:4:346:14|M
