@TM:1272359942
@N: CD630 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\fusion.vhd":1491:10:1491:13|M
@N: CD630 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\fusion.vhd":1899:10:1899:12|M
@N: CD630 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\fusion.vhd":2117:10:2117:12|M
@N: CD630 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\fusion.vhd":2179:10:2179:12|M
@N: CD630 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\fusion.vhd":2381:10:2381:12|M
@N: CD630 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\fusion.vhd":3019:10:3019:12|M
@N: CD630 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\fusion.vhd":3149:10:3149:13|M
@N: CD630 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\fusion.vhd":3182:10:3182:15|M
@N: CD720 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\vhd\std.vhd":123:18:123:21|M
@N: CD630 :"C:\Actelprj\AFS_ADV_KIT_8051\hdl\memory_interface.vhd":7:7:7:12|M
@W: CD638 :"C:\Actelprj\AFS_ADV_KIT_8051\hdl\memory_interface.vhd":46:7:46:16|M
@W: CD638 :"C:\Actelprj\AFS_ADV_KIT_8051\hdl\memory_interface.vhd":47:7:47:16|M
@W: CD638 :"C:\Actelprj\AFS_ADV_KIT_8051\hdl\memory_interface.vhd":48:7:48:16|M
@N: CD630 :"C:\Actelprj\AFS_ADV_KIT_8051\smartgen\INT_RAM8kX8\INT_RAM8kX8.vhd":8:7:8:17|M
@W: CL168 :"C:\Actelprj\AFS_ADV_KIT_8051\smartgen\INT_RAM8kX8\INT_RAM8kX8.vhd":346:4:346:14|M
